# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
      - '*.md'
      - '.github/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  golint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          
  test:
    needs: [golint]
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.6

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
          
          
  push_to_registry:
    needs: [test]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: giasopas/piumossov
      
      - name: Build and push Docker imagee
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
   
      
  cd_process:
    name: Push zip file to s3
    runs-on: ubuntu-latest
    needs: [push_to_registry]
    
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2 
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: eu-central-1
           
           
      - name: Deploy
        run : |
            zip -r deployment-${{ github.sha }}.zip Dockerrun.aws.json
            aws s3 cp deployment-${{ github.sha }}.zip s3://go-app-eb
            aws elasticbeanstalk create-application-version --application-name goapp \
                --version-label ${{ github.sha }} --source-bundle S3Bucket="go-app-eb",S3Key="deployment-${{ github.sha }}.zip"
            aws elasticbeanstalk update-environment --application-name goapp \
                --environment-name Goapp-env --version-label ${{ github.sha }}
  
